name: finder_matcher_generator
description: A Flutter package for generating custom Finders and Matchers for widget tests.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  analyzer: 
  build:
  equatable: ^2.0.5
  finder_matcher_gen: 
    git: 
      url: https://github.com/JasperEssien2/finder-matcher-gen.git
      ref: master
      path: packages/finder_matcher_gen
  meta: ^1.8.0
  path: ^1.8.2
  source_gen:   
  

dev_dependencies:
  build_runner:
  build_test:
  finder_matcher_generator: 
    git: 
      url: https://github.com/JasperEssien2/finder-matcher-gen.git
      ref: master
      path: packages/finder_matcher_generator
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
