name: finder_matcher_annotation
description: A Flutter package containing annotations to mark widgets for finder_matcher_gen.
version: 0.1.1
repository: https://github.com/JasperEssien2/finder-matcher-gen
issue_tracker: https://github.com/JasperEssien2/finder-matcher-gen/issues
homepage: https://jasperessien2.github.io/finder-matcher-gen/

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
