targets:
  $default:
    sources:
      - integration_test/**
      - lib/**
      - pubspec.*
      - $package$
    builders:
      finder_matcher_gen|finder_matcher_annotation:
        enabled: true
 

builders:
  finder_matcher_gen:
    import: "package:finder_matcher_gen/builder.dart"
    builder_factories: ["generateFinder", "generateMatcher"]
    build_extensions: {".dart": [".finders.dart", ".matchers.dart"]}
    auto_apply: dependents
    build_to: "source"
