builders:
  finder_matcher_gen:
    import: "package:finder_matcher_gen/builder.dart"
    builder_factories: ["generateFinder", "generateMatcher"]
    build_extensions: {".dart": [".finders.dart", ".matchers.dart"]}
    auto_apply: dependents
    build_to: "source"
