name: finder_matcher_gen
description: A Flutter package for generating custom Finders and Matchers for widget tests.
version: 0.1.0
repository: https://github.com/JasperEssien2/finder-matcher-gen
issue_tracker: https://github.com/JasperEssien2/finder-matcher-gen/issues
homepage: https://jasperessien2.github.io/finder-matcher-gen/


environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  analyzer: ^5.3.1
  analyzer_plugin: ^0.11.2 
  build: ^2.3.1
  custom_lint_builder: ^0.0.16
  equatable: ^2.0.5
  finder_matcher_annotation: ^0.1.0
  meta: ^1.8.0
  path: ^1.8.2
  source_gen:  ^1.2.6
  
dev_dependencies:
  build_runner:
  build_test:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
