name: finder_matcher_generator
description: A Flutter package for generating custom Finders and Matchers for widget tests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  build:
  source_gen: 
  finder_matcher_gen: 
    path: ../finder_matcher_gen/
  analyzer: 
  path: ^1.8.2

dev_dependencies:
  build_test:
  build_runner:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
